routes/web.php
<?php

use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['as' => 'users.', 'middleware' => 'auth'], function () {
    Route::get('users', [UserController::class, 'index'])
        ->name('index')
        ->middleware('permission:index-user');
    Route::get('users/{user}', [UserController::class, 'show'])
        ->name('show')
        ->where('user', '[0-9]+')
        ->middleware('permission:index-user');
    Route::get('/users/search/user', [UserController::class, 'search'])
        ->name('search')
        ->middleware('permission:index-user');;
    Route::get('users/create', [UserController::class, 'create'])
        ->name('create')
        ->middleware('permission:create-user');
    Route::post('users', [UserController::class, 'store'])
        ->name('store')
        ->middleware('permission:create-user');
    Route::get('users/{user}/edit', [UserController::class, 'edit'])
        ->name('edit')
        ->middleware(['permission:edit-user', 'check.user']);
    Route::put('users/{user}', [UserController::class, 'update'])
        ->name('update')
        ->middleware(['permission:edit-user', 'check.user']);
    Route::delete('users/{user}', [UserController::class, 'destroy'])
        ->name('destroy')
        ->middleware(['permission:delete-user', 'check.user']);
});

Route::group(['as' => 'roles.', 'middleware' => 'auth'], function () {
    Route::get('roles', [RoleController::class, 'index'])
        ->name('index')
        ->middleware('permission:index-role');
    Route::get('roles/{role}', [RoleController::class, 'show'])
        ->name('show')
        ->where('role', '[0-9]+')
        ->middleware('permission:index-role');
    Route::get('/roles/search/role', [RoleController::class, 'search'])
        ->name('search')
        ->middleware('permission:index-role');
    Route::get('roles/create', [RoleController::class, 'create'])
        ->name('create')
        ->middleware('permission:create-role');
    Route::post('roles', [RoleController::class, 'store'])
        ->name('store')
        ->middleware('permission:create-role');
    Route::get('roles/{role}/edit', [RoleController::class, 'edit'])
        ->name('edit')
        ->middleware(['permission:edit-role', 'canNotModifyRoleSuperAdmin']);
    Route::put('roles/{role}', [RoleController::class, 'update'])
        ->name('update')
        ->middleware(['permission:edit-role', 'canNotModifyRoleSuperAdmin']);
    Route::delete('roles/{role}', [RoleController::class, 'destroy'])
        ->name('destroy')
        ->middleware(['permission:delete-role', 'canNotModifyRoleSuperAdmin']);
});

Route::group(['as' => 'categories.', 'middleware' => 'auth', 'prefix' => 'categories'], function () {
    Route::get('/', [CategoryController::class, 'index'])
        ->name('index')
        ->middleware('permission:index-category');
    Route::get('/list', [CategoryController::class, 'list'])
        ->name('list')
        ->middleware('permission:index-category');
    Route::get('/getParentCategories', [CategoryController::class, 'getParentCategories'])
        ->name('getParentCategories')
        ->middleware('permission:index-category');
    Route::post('/', [CategoryController::class, 'store'])
        ->name('store')
        ->middleware('permission:create-category');
    Route::get('/{category}/edit', [CategoryController::class, 'edit'])
        ->name('edit')
        ->middleware('permission:edit-category');
    Route::put('/{category}', [CategoryController::class, 'update'])
        ->name('update')
        ->middleware('permission:edit-category');
    Route::delete('/{category}', [CategoryController::class, 'destroy'])
        ->name('destroy')
        ->middleware('permission:delete-category');
});

Route::group(['as' => 'products.', 'middleware' => 'auth'], function () {
    Route::get('products', [ProductController::class, 'index'])
        ->name('index')
        ->middleware('permission:index-product');
    Route::get('products/{product}', [ProductController::class, 'show'])
        ->name('show')
        ->where('product', '[0-9]+')
        ->middleware('permission:index-product');
    Route::get('/products/search/product', [ProductController::class, 'search'])
        ->name('search')
        ->middleware('permission:index-product');
    Route::get('products/create', [ProductController::class, 'create'])
        ->name('create')
        ->middleware('permission:create-product');
    Route::post('products', [ProductController::class, 'store'])
        ->name('store')
        ->middleware('permission:create-product');
    Route::get('products/{product}/edit', [ProductController::class, 'edit'])
        ->name('edit')
        ->middleware('permission:edit-product');
    Route::put('products/{product}', [ProductController::class, 'update'])
        ->name('update')
        ->middleware('permission:edit-product');
    Route::delete('products/{product}', [ProductController::class, 'destroy'])
        ->name('destroy')
        ->middleware('permission:delete-product');
});

app/Models/Role.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use HasFactory;

    protected $table = 'roles';

    protected $fillable = [
        'name',
        'display_name',
    ];

    public function scopeWithName($query, $name)
    {
        return $name ? $query->where('display_name', 'LIKE', "%{$name}%") : null;
    }

    public function scopeGetRoleWithOutSuperAdmin($query)
    {
        return $query->where('name', '!=', 'super-admin');
    }

    public function assignPermissions($permissionIds)
    {
        return $this->permissions()->attach($permissionIds);
    }

    public function syncPermissions($permissionIds)
    {
        return $this->permissions()->sync($permissionIds);
    }

    public function users()
    {
        return $this->belongsToMany(User::class, 'user_role', 'role_id', 'user_id')
            ->withTimestamps();
    }

    public function permissions()
    {
        return $this->belongsToMany(Permission::class, 'role_permission', 'role_id', 'permission_id')
            ->withTimestamps();
    }
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Role\RoleRequest;
use App\Services\PermissionService;
use Illuminate\Support\Facades\View;
use Illuminate\Http\Request;
use App\Services\RoleService;

class RoleController extends Controller
{
    protected $roleService;
    protected $permissionService;

    public function __construct(RoleService $roleService, PermissionService $permissionService)
    {
        $this->roleService = $roleService;
        $this->permissionService = $permissionService;
        View::share('permissions', $this->permissionService->getPermissions());
    }

    public function index(Request $request)
    {
        $roles = $this->roleService->search($request);
        return view('admin.roles.index', compact('roles', 'request'));
    }

    public function create()
    {
        return view('admin.roles.create');
    }

    public function store(RoleRequest $request)
    {
        $this->roleService->create($request);
        return redirect()->route('roles.index')->with('success', 'Create Role Success !!!');
    }

    public function show($id)
    {
        $role = $this->roleService->findById($id);
        return view('admin.roles.show', compact('role'));
    }

    public function edit($id)
    {
        $role = $this->roleService->findById($id);
        return view('admin.roles.edit', compact('role'));
    }

    public function update(RoleRequest $request, $id)
    {
        $this->roleService->update($request, $id);
        return redirect()->route('roles.index')->with('update', 'Update Role Success !!!');
    }

    public function destroy($id)
    {
        $this->roleService->delete($id);
        return redirect()->route('roles.index');
    }
}

resources/views/admin/roles/create.blade.php
@extends('layouts.template')

@section('content')
    <div class="container-fluid">
        <div class="row pt-3 w-100">
            <div class="col d-flex">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                     class="bi bi-box-arrow-right mt-2 text-success" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                    <path fill-rule="evenodd"
                          d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                </svg>&ensp;
                <h1 class="font-weight-bold">Create Role</h1>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-8 mt-5">
                <div class="card">
                    <div class="card-header">
                        <ul class="nav nav-pills">
                            <li class="nav-item"><a class="nav-link active bg-info">Create Role</a></li>
                        </ul>
                    </div><!-- /.card-header -->
                    <div class="card-body">
                        <form action="{{ route('roles.store') }}" method="post">
                            @csrf
                            <div class="form-group">
                                <label for="name">Name :</label>
                                <input type="text" class="form-control" name="name" placeholder="Name"
                                       value="{{ old('name') }}">
                                @if($errors->has('name'))
                                    <p class="text-danger">{{$errors->first('name')}}</p>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="display_name">Display Name :</label>
                                <input type="text" class="form-control" name="display_name" placeholder="Display Name"
                                       value="{{ old('display_name') }}">
                                @if($errors->has('display_name'))
                                    <p class="text-danger">{{$errors->first('display_name')}}</p>
                                @endif
                            </div>
                            <br>
                            <div>
                                @foreach($permissions as $permission)
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" value="{{ $permission->id }}"
                                               name="permission_ids[]">
                                        <label class="form-check-label">
                                            {{ $permission->display_name }}
                                        </label>
                                    </div>
                                @endforeach
                            </div>
                            <button type="submit" class="btn btn-success mt-3">Create</button>
                            <a href="{{ route('roles.index') }}" class="btn btn-primary float-right mt-3"><i
                                    class="fas fa-home"></i>&nbsp;&nbsp;Home</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/edit.blade.php
@extends('layouts.template')

@section('content')
    <div class="container-fluid">
        <div class="row pt-3 w-100">
            <div class="col d-flex">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                     class="bi bi-box-arrow-right mt-2 text-success" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                    <path fill-rule="evenodd"
                          d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                </svg>&ensp;
                <h1 class="font-weight-bold">Edit Role</h1>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-8 mt-5">
                <div class="card">
                    <div class="card-header">
                        <ul class="nav nav-pills">
                            <li class="nav-item"><a class="nav-link active bg-info">Role Edit - {{ $role->id }}</a></li>
                        </ul>
                    </div><!-- /.card-header -->
                    <div class="card-body">
                        <form action="{{ route('roles.update', $role->id) }}" method="post">
                            @csrf
                            @method('put')
                            <div class="form-group">
                                <label for="name">Name :</label>
                                <input type="text" class="form-control" name="name" placeholder="Name"
                                       value="{{$role->name}}">
                                @if($errors->has('name'))
                                    <p class="text-danger">{{$errors->first('name')}}</p>
                                @endif
                            </div>
                            <div class="form-group">
                                <label for="display_name">Display Name :</label>
                                <input type="text" class="form-control" name="display_name" placeholder="Display Name"
                                       value="{{$role->display_name}}">
                                @if($errors->has('display_name'))
                                    <p class="text-danger">{{$errors->first('display_name')}}</p>
                                @endif
                            </div>
                            <br>
                            <div>
                                @foreach($permissions as $permission)
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" value="{{ $permission->id }}"
                                               @if(in_array($permission->id,$role->permissions()->pluck('id')->toArray())) checked
                                               @endif
                                               name="permission_ids[]"
                                        >
                                        <label class="form-check-label">
                                            {{ $permission->display_name }}
                                        </label>
                                    </div>
                                @endforeach
                            </div>
                            <br>
                            <button type="submit" class="btn btn-success">Update</button>
                            <a href="{{ route('roles.index') }}" class="btn btn-primary float-right"><i
                                    class="fas fa-home"></i>&nbsp;&nbsp;Home</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/roles/index.blade.php
@extends('layouts.template')

@section('content')
    <div class="container-fluid">
        <div class="row pt-3 w-100">
            <div class="col d-flex">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                     class="bi bi-box-arrow-right mt-2 text-success" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                    <path fill-rule="evenodd"
                          d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                </svg>&ensp;
                <h1 class="font-weight-bold">All Roles</h1>
            </div>
            @hasPermission('create-role')
            <div class="col d-flex justify-content-end">
                <a href="{{ route('roles.create') }}" class="btn btn-primary btn-lg mt-1">Create Role</a>
            </div>
            @endhasPermission
        </div>
        <div class="row justify-content-between">
            <div class="container">
                <div class="row d-flex justify-content-center">
                    <div class="col-md-10">
                        <form action="{{ route('roles.index') }}" class="card p-3 py-4 mt-3" method="get">
                            <div class="row g-3 mt-2 justify-content-center">
                                <div class="col-md-6"><input type="search" class="form-control"
                                                             placeholder="Enter Name ..." name="name"
                                                             value="{{ $request['name'] }}"></div>
                                <div class="col-md-3">
                                    <button type="submit" class="btn btn-secondary btn-block">Search Results</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        @if (session('success'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('success') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        @if (session('update'))
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ session('update') }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        @endif
        <div class="row justify-content-center">
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th scope="col" width="200px">#</th>
                    <th scope="col" width="400px">DISPLAY NAME</th>
                    <th scope="col" width="200px">COUNT USER</th>
                    <th scope="col" width="600px">PERMISSION</th>
                    <th scope="col" style="padding-left: 50px">ACTION</th>
                </tr>
                </thead>
                <tbody>
                @forelse($roles as $role)
                    <tr>
                        <th scope="row">{{ $role->id }}</th>
                        <td>{{ $role->display_name }}</td>
                        <td style="padding-left: 50px">
                            <span class="badge badge-success">{{ $role->users->count() }}</span>
                        </td>
                        <td>
                            @foreach($role->permissions as $permission)
                                <span class="badge badge-info">{{$permission->display_name}}</span>
                            @endforeach
                        </td>
                        <td>
                            <a href="{{ route('roles.show',$role->id) }}" class="btn btn-primary float-left mr-1">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-eye" viewBox="0 0 16 16">
                                    <path
                                        d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.133 13.133 0 0 1 1.66-2.043C4.12 4.668 5.88 3.5 8 3.5c2.12 0 3.879 1.168 5.168 2.457A13.133 13.133 0 0 1 14.828 8c-.058.087-.122.183-.195.288-.335.48-.83 1.12-1.465 1.755C11.879 11.332 10.119 12.5 8 12.5c-2.12 0-3.879-1.168-5.168-2.457A13.134 13.134 0 0 1 1.172 8z"/>
                                    <path
                                        d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
                                </svg>
                            </a>
                            @hasPermission('edit-role')
                            <a href="{{ route('roles.edit',$role->id) }}" class="btn btn-warning float-left mr-1">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-pencil" viewBox="0 0 16 16">
                                    <path
                                        d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                </svg>
                            </a>
                            @endhasPermission
                            @hasPermission('delete-role')
                            <a class="btn btn-danger" onclick="deleteRole({{ $role->id }})">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-trash" viewBox="0 0 16 16">
                                    <path
                                        d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                                    <path fill-rule="evenodd"
                                          d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                                </svg>
                            </a>
                            @endhasPermission
                            <form id="delete-{{$role->id}}" action="{{ route('roles.destroy',$role->id) }}"
                                  method="post" style="display: none">
                                @csrf
                                @method('delete')
                            </form>
                        </td>
                    </tr>
                @empty
                    <p class="font-weight-bold"> -- NOT FOUND DATA -- </p>
                @endforelse
                </tbody>
            </table>
            {{ $roles->links() }}
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        function deleteRole(id) {
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    event.preventDefault();
                    document.getElementById('delete-' + id).submit();
                    Swal.fire(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success'
                    )
                }
            })
        }
    </script>
@endpush

resources/views/admin/roles/show.blade.php
@extends('layouts.template')

@section('content')
    <div class="container-fluid">
        <div class="row pt-3 w-100">
            <div class="col d-flex">
                <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                     class="bi bi-box-arrow-right mt-2 text-success" viewBox="0 0 16 16">
                    <path fill-rule="evenodd"
                          d="M10 12.5a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h8a.5.5 0 0 1 .5.5v2a.5.5 0 0 0 1 0v-2A1.5 1.5 0 0 0 9.5 2h-8A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h8a1.5 1.5 0 0 0 1.5-1.5v-2a.5.5 0 0 0-1 0v2z"/>
                    <path fill-rule="evenodd"
                          d="M15.854 8.354a.5.5 0 0 0 0-.708l-3-3a.5.5 0 0 0-.708.708L14.293 7.5H5.5a.5.5 0 0 0 0 1h8.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3z"/>
                </svg>&ensp;
                <h1 class="font-weight-bold">Role Detail</h1>
            </div>
        </div>
        <div class="row justify-content-between">
            <div class="container">
                <div class="row mb-3 mt-5">
                    <div class="card w-100">
                        <div class="card-header">
                            <ul class="nav nav-pills">
                                <li class="nav-item"><a class="nav-link active bg-info">Role Detail
                                        - {{ $role->id }}</a></li>
                            </ul>
                        </div><!-- /.card-header -->
                        <div class="card-body">
                            <h5 class="card-title">
                                <span class="font-weight-bold">Display Name :</span>&nbsp;&nbsp;
                                <span class="badge bg-success">{{ $role->display_name }}</span>
                            </h5>
                            <br><br>
                            <p class="card-text">
                                User Count : {{ $role->users()->count() }}
                            </p>
                            <h5>Permission</h5>

                            @foreach($role->permissions as $permission)
                                <span class="badge badge-info">{{$permission->display_name}}</span>
                            @endforeach
                            <br>
                            <br>
                            <a href="{{ route('roles.edit',$role->id) }}" class="btn btn-warning">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-pencil" viewBox="0 0 16 16">
                                    <path
                                        d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                                </svg>
                            </a>
                            <a href="{{ route('roles.index') }}" class="btn btn-primary float-right"><i
                                    class="fas fa-home"></i>&nbsp;&nbsp;Home</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection